---
- hosts: nomad_instances
  become: yes

  vars:
    volume: /dev/disk/by-id/scsi-0DO_Volume_consul-data
    mount_volume: "{{ ansible_hostname == 'nomad1' and ansible_system_vendor == 'DigitalOcean' }}"
    data_dir: "{{ mount_volume | ternary('/data', '/var/consul') }}"

  pre_tasks:

  - name: Disable Firewall
    service: name=ufw state=stopped

  - name: Install HTTPS Apt Packages
    apt: name={{ item }} update_cache=yes
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

  - name: Add Docker GPG Key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

  - name: Add Docker Repository
    apt_repository:
      repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state=present

  - name: Install Docker CE
    apt: name=docker-ce state=present update_cache=yes

  - name: Enable Docker at Startup
    service: name=docker state=started enabled=yes

  - name: add user mod to docker
    command: usermod -aG docker {{ ansible_user }}

  - name: Install pip
    apt: name=python-pip

  - name: Install Python Packages
    pip: name={{ item }}
    with_items:
    - docker-py


  - name: Create Volume Filesystem
    filesystem: fstype=xfs dev={{ volume }}
    when: mount_volume

  - name: Mount Volume
    mount: path={{ data_dir }} src={{ volume }} fstype=xfs state=mounted
    when: mount_volume

  roles:

    - role: brianshumate.nomad
      nomad_bind_address: 0.0.0.0
      nomad_docker_enable: yes
      #nomad_config_custom:
      #  client:
      #    options: {\"docker.cleanup.image\"=\"false\"}
            


    - role: brianshumate.consul
# May 22 18:07:27 ubuntu-xenial consul[13074]: ==> Advertise address cannot be 0.0.0.0, :: or [::]
# sudo journalctl -u consul.service
      consul_client_address: 0.0.0.0
#      consul_bind_address: 0.0.0.0
      consul_data_path: "{{ data_dir }}"
      consul_encrypt_enable: false
#      consul_raw_key: '123456'


  # Keeping last since slow when debugging roles.
  tasks:
    - name: Pull Docker Astor-D4j Image
      docker_image: name=chrisparnin/astor-d4j

    - name: copy our custom nomad agent settings (do not purge image after run). 
      copy: src=templates/custom.hcl dest=/etc/nomad.d/custom.hcl mode=744

    - name: restart nomad
      service: name=nomad state=restarted